Exit when failing to download dxvk-async patch if enabled
Fixes https://github.com/Frogging-Family/dxvk-tools/issues/15

diff --git a/updxvk b/updxvk
--- a/updxvk
+++ b/updxvk
@@ -107,7 +107,9 @@ fi
 GIT_HEAD=$(git rev-parse HEAD)-`date '+%Y-%m-%d-%H:%M:%S'`
 
 if [ "$_async" == "true" ]; then
-  wget -O ../DXVKBUILD/patches/dxvk-async.dxvkpatchb https://raw.githubusercontent.com/Sporif/dxvk-async/master/dxvk-async.patch
+  if ! wget -O ../DXVKBUILD/patches/dxvk-async.dxvkpatchb https://raw.githubusercontent.com/Sporif/dxvk-async/master/dxvk-async.patch; then
+    echo -e "\nFailed to download dxvk-async patch. Make sure wget installed." && exit 1
+  fi
   mv ../DXVKBUILD/patches/dxvk-async.dxvkpatchb ../DXVKBUILD/patches/dxvk-async.dxvkpatch 2>/dev/null
 else
   mv ../DXVKBUILD/patches/dxvk-async.dxvkpatch ../DXVKBUILD/patches/dxvk-async.dxvkpatchb 2>/dev/null
